// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BankTest.Models
{
    public partial class User
    {
        [Key]
        [StringLength(50)]
        public string LoginName { get; set; }
        [StringLength(32)]
        public string PswHash { get; set; }
        [StringLength(36)]
        public string Salt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? TimeStamp { get; set; }
    }
}